spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/risk_db?autoReconnect=true&useSSL=false&characterEncoding=utf8
    username: admin
    password: admin
  
  data:
    redis:
      host: localhost
      port: 6379
      password:
  
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8083

logging:
  level:
    root: INFO
    com.banking: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  public-key-path: ./keys/public_key.pem
  issuer: banking-identity-service

external:
  otp-service:
    url: http://localhost:8082/api/v1/otp
  identity-service:
    url: http://localhost:8081/api/v1/auth
