spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db?autoReconnect=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: banking-notification-service-consumer-group-dev
  
  mail:
    host: smtp.gmail.com
    port: 587

server:
  port: 8091

management:
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    com.banking.notification: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.mail: DEBUG

notification:
  email:
    enabled: true
  sms:
    enabled: false
  push:
    enabled: false

springdoc:
  swagger-ui:
    enabled: true
