apiVersion: v1
kind: Service
metadata:
  name: speech-to-text-service
  namespace: banking-platform
  labels:
    app: speech-to-text-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8019"
    prometheus.io/path: "/api/actuator/prometheus"
spec:
  type: ClusterIP
  selector:
    app: speech-to-text-service
  ports:
    - name: http
      port: 8019
      targetPort: 8019
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
