apiVersion: v1
kind: Service
metadata:
  name: i18n-service
  namespace: banking
  labels:
    app: i18n-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: i18n-service
  ports:
    - name: http
      port: 8017
      targetPort: 8017
      protocol: TCP
  sessionAffinity: None
