spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?autoReconnect=true&useSSL=true&sslmode=require&characterEncoding=utf8
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  
  jpa:
    show-sql: false
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512

server:
  port: 8080

logging:
  level:
    root: INFO
    com.banking: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN

otp:
  ttl-seconds: 300
  max-attempts: 3

management:
  endpoint:
    health:
      show-details: when-authorized
