spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/banking_ai_insights?autoReconnect=true&useSSL=true&characterEncoding=utf8
  
  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    com.banking.insight: INFO

insight:
  generation:
    enabled: true
  anomaly:
    detection:
      enabled: true
  recommendation:
    enabled: true
