apiVersion: v1
kind: Service
metadata:
  name: otp-service
  namespace: banking-platform
  labels:
    app: otp-service
    tier: backend
    component: security
spec:
  type: ClusterIP
  selector:
    app: otp-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  sessionAffinity: None
