spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SSL

logging:
  level:
    root: WARN
    com.banking: INFO
    org.springframework.web: ERROR
    org.springframework.security: WARN

account:
  cache:
    balance-ttl: 5
    details-ttl: 15

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
