spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  
  jpa:
    show-sql: false
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

logging:
  level:
    root: INFO
    com.banking: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN

account:
  cache:
    balance-ttl: 5
    details-ttl: 15
