apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
data:
  database.url: "jdbc:postgresql://postgres:5432/banking_transaction"
  redis.host: "redis"
  redis.port: "6379"
  kafka.bootstrap-servers: "kafka:9092"
  account-service.url: "http://account-service:8086/api"
