apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  db.host: "postgres-service"
  db.port: "5432"
  db.name: "notification_db"
  redis.host: "redis-service"
  redis.port: "6379"
  kafka.bootstrap-servers: "kafka-service:9092"
  smtp.host: "smtp.gmail.com"
  smtp.port: "587"
  email.from: "noreply@banking.com"
  email.from-name: "Banking Platform"
  twilio.from-number: "+1234567890"
