--liquibase formatted sql

--changeset account-service:1
--comment: Create account table with all required fields

CREATE TABLE account (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    account_number VARCHAR(50) NOT NULL UNIQUE,
    iban VARCHAR(34) UNIQUE,
    account_type VARCHAR(20) NOT NULL,
    account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    balance DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    available_balance DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    hold_balance DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    overdraft_limit DECIMAL(19, 2) DEFAULT 0.00,
    interest_rate DECIMAL(5, 4) DEFAULT 0.0000,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    last_transaction_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_account_type CHECK (account_type IN ('SAVINGS', 'CHECKING', 'CREDIT')),
    CONSTRAINT chk_account_status CHECK (account_status IN ('ACTIVE', 'INACTIVE', 'FROZEN', 'CLOSED')),
    CONSTRAINT chk_balance_non_negative CHECK (balance >= 0 OR account_type = 'CREDIT'),
    CONSTRAINT chk_available_balance_non_negative CHECK (available_balance >= 0 OR account_type = 'CREDIT'),
    CONSTRAINT chk_hold_balance_non_negative CHECK (hold_balance >= 0)
);

COMMENT ON TABLE account IS 'Core account table storing all account types with balance information';
COMMENT ON COLUMN account.id IS 'Primary key UUID';
COMMENT ON COLUMN account.user_id IS 'Foreign key to user service (not enforced cross-service)';
COMMENT ON COLUMN account.account_number IS 'Unique account number generated by service';
COMMENT ON COLUMN account.iban IS 'International Bank Account Number (optional)';
COMMENT ON COLUMN account.account_type IS 'Type of account: SAVINGS, CHECKING, CREDIT';
COMMENT ON COLUMN account.account_status IS 'Current status: ACTIVE, INACTIVE, FROZEN, CLOSED';
COMMENT ON COLUMN account.currency IS 'ISO 4217 currency code';
COMMENT ON COLUMN account.balance IS 'Current balance (scale=2, HALF_UP)';
COMMENT ON COLUMN account.available_balance IS 'Available balance after holds';
COMMENT ON COLUMN account.hold_balance IS 'Amount currently on hold';
COMMENT ON COLUMN account.overdraft_limit IS 'Overdraft limit for checking accounts';
COMMENT ON COLUMN account.interest_rate IS 'Annual interest rate (percentage as decimal)';
COMMENT ON COLUMN account.opened_at IS 'Account opening timestamp';
COMMENT ON COLUMN account.closed_at IS 'Account closure timestamp';
COMMENT ON COLUMN account.last_transaction_at IS 'Last transaction timestamp';
COMMENT ON COLUMN account.version IS 'Optimistic locking version';

--rollback DROP TABLE account;
