apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  db.url: "jdbc:postgresql://postgres-service:5432/user_db?autoReconnect=true&useSSL=true&characterEncoding=utf8"
  redis.host: "redis-service"
  redis.port: "6379"
  kafka.bootstrap.servers: "kafka-service:9092"
  user.cache.profile-ttl: "15"
  user.cache.preference-ttl: "30"
  user.kyc.document-max-size: "10"
  user.kyc.expiry-days: "365"
