apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: banking-platform
  labels:
    app: chat-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8086"
    prometheus.io/path: "/api/actuator/prometheus"
spec:
  type: ClusterIP
  selector:
    app: chat-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      protocol: TCP
  sessionAffinity: None
