package com.banking.audit.domain;

public enum EventType {
    // Account Events
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_CLOSED,
    ACCOUNT_STATUS_CHANGED,
    ACCOUNT_BALANCE_UPDATED,
    
    // Transaction Events
    TRANSACTION_CREATED,
    TRANSACTION_EXECUTED,
    TRANSACTION_REVERSED,
    TRANSACTION_FAILED,
    
    // User Events
    USER_REGISTERED,
    USER_UPDATED,
    USER_DELETED,
    USER_LOGIN,
    USER_LOGOUT,
    USER_PASSWORD_CHANGED,
    USER_EMAIL_VERIFIED,
    USER_PHONE_VERIFIED,
    
    // Authentication Events
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILED,
    AUTH_LOGOUT,
    AUTH_TOKEN_REFRESHED,
    AUTH_TOKEN_REVOKED,
    AUTH_PASSWORD_RESET_REQUESTED,
    AUTH_PASSWORD_RESET_COMPLETED,
    
    // MFA Events
    MFA_ENABLED,
    MFA_DISABLED,
    MFA_VERIFIED,
    MFA_FAILED,
    OTP_GENERATED,
    OTP_VERIFIED,
    OTP_FAILED,
    
    // Device Events
    DEVICE_REGISTERED,
    DEVICE_TRUSTED,
    DEVICE_BLOCKED,
    DEVICE_REMOVED,
    
    // Fraud Events
    FRAUD_ALERT_RAISED,
    FRAUD_ALERT_RESOLVED,
    FRAUD_RULE_TRIGGERED,
    FRAUD_SCORE_CALCULATED,
    
    // Risk Events
    RISK_ASSESSMENT_PERFORMED,
    RISK_LEVEL_CHANGED,
    
    // Admin Events
    ADMIN_USER_CREATED,
    ADMIN_USER_UPDATED,
    ADMIN_USER_DELETED,
    ADMIN_ROLE_ASSIGNED,
    ADMIN_ROLE_REVOKED,
    ADMIN_PERMISSION_GRANTED,
    ADMIN_PERMISSION_REVOKED,
    ADMIN_CONFIG_CHANGED,
    
    // System Events
    SYSTEM_CONFIG_UPDATED,
    SYSTEM_MAINTENANCE_STARTED,
    SYSTEM_MAINTENANCE_COMPLETED,
    SYSTEM_ERROR_OCCURRED,
    
    // Generic Events
    ENTITY_CREATED,
    ENTITY_UPDATED,
    ENTITY_DELETED,
    ENTITY_ACCESSED
}
